### ISSUE TITLE
500 error when trying to access.

### ISSUE THREAD

**Issue by bradholland** [vigstudio/vig-theme-editor#2]
Upon installing the plugin in martfury (botble) the page returns a 500 error.

**Comment by vigstudio** [comment]
can you open debug mode and send me a picture of its error?

**Comment by bradholland** [comment]
sure will do, I will do so in the morning. 
and thank you.

**Comment by bradholland** [comment]
Hey Vig, 
this is the error shown. 
thanks again
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/47755928/234005417-e951a354-f41b-49c0-a876-43a65938413a.png">

**Comment by bradholland** [comment]
Perhaps it doesn't work with botble martfury, only cms?

**Comment by vigstudio** [comment]
https://marketplace.botble.com/products/vigstudio/vig-theme-editor 
Support BotbleCMS news core.
You can reinstall  it

**Comment by bradholland** [comment]
perfect! well done sir!
